SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(SUB.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID 
JOIN 
(SELECT *
FROM BOOK_SALES BS
WHERE BS.SALES_DATE LIKE '2022-01%') SUB
ON SUB.BOOK_ID = B.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC