SELECT IT2.ITEM_ID,II.ITEM_NAME, II.RARITY
FROM ITEM_TREE IT RIGHT JOIN
ITEM_TREE IT2 ON IT.PARENT_ITEM_ID = IT2.ITEM_ID
JOIN ITEM_INFO II ON II.ITEM_ID = IT2.ITEM_ID 
WHERE IT.ITEM_ID IS NULL
ORDER BY IT2.ITEM_ID DESC