SELECT DISTINCT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE * (1-(DISCOUNT_RATE / 100)) * 30) AS "FEE"
FROM
(SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = "세단" OR CAR_TYPE = "SUV") CAR
JOIN 
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN(
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE  <= 20221130 AND END_DATE >= 20221101))) HISTORY
ON CAR.CAR_ID = HISTORY.CAR_ID
JOIN
(SELECT PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = "30일 이상" AND (CAR_TYPE = "세단" OR CAR_TYPE = "SUV")) PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.DAILY_FEE * (1-(DISCOUNT_RATE / 100)) * 30 >= 500000
AND CAR.DAILY_FEE * (1-(DISCOUNT_RATE / 100)) * 30 < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC;