SELECT DISTINCT CC.CAR_ID, CC.CAR_TYPE, ROUND(CC.DAILY_FEE * 30 * ((100-CP.DISCOUNT_RATE) /100),0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON CC.CAR_ID = CH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP ON CP.CAR_TYPE = CC.CAR_TYPE
WHERE (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
AND CC.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '20221130'AND END_DATE >= '20221101')
AND CP.DURATION_TYPE = '30일 이상'
AND CC.DAILY_FEE * 30 * ((100-CP.DISCOUNT_RATE) /100) >= 500000
AND CC.DAILY_FEE * 30 * ((100-CP.DISCOUNT_RATE) /100) < 2000000
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC

 
 
 
 

