WITH TEMP AS (SELECT *
FROM USER_INFO U
WHERE YEAR(U.JOINED) = '2021')

SELECT YEAR(O.SALES_DATE) AS 'YEAR',
MONTH(O.SALES_DATE) AS 'MONTH',
COUNT(DISTINCT O.USER_ID) AS 'PURCHASED_USERS',
ROUND(COUNT(DISTINCT O.USER_ID) / TOTAL.TOTAL_CNT,1) AS 'PURCHASED_RATIO'
FROM ONLINE_SALE O 
JOIN TEMP T ON O.USER_ID = T.USER_ID 
JOIN (SELECT COUNT(*) AS TOTAL_CNT FROM TEMP) TOTAL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR, MONTH
