WITH REVIEWS AS (
    SELECT R.MEMBER_ID
    FROM REST_REVIEW R
    GROUP BY R.MEMBER_ID
    ORDER BY COUNT(R.MEMBER_ID) DESC
    LIMIT 1
    )
    
SELECT M.MEMBER_NAME, RV.REVIEW_TEXT, DATE_FORMAT(RV.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REVIEWS R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN REST_REVIEW RV 
ON RV.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT