WITH TEMP AS (SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE C.START_DATE >= '20220801'
AND C.START_DATE <= '20221031'
GROUP BY C.CAR_ID
HAVING COUNT(C.CAR_ID) >= 5)

SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE C.CAR_ID IN (SELECT CAR_ID FROM TEMP)
AND START_DATE >= '2022-08-01'
AND START_DATE <= '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
ORDER BY MONTH, C.CAR_ID DESC
