
SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, (MAXS - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA D
JOIN
(SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEARS, MAX(E.SIZE_OF_COLONY) AS MAXS
FROM ECOLI_DATA E
GROUP BY YEAR(E.DIFFERENTIATION_DATE)) ED
ON YEAR(D.DIFFERENTIATION_DATE) = ED.YEARS
ORDER BY YEAR, YEAR_DEV
