
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_COLONY - SIZE_OF_COLONY AS YEAR_DEV,ID
FROM ECOLI_DATA E2
JOIN
(SELECT YEAR(E1.DIFFERENTIATION_DATE) AS MAX_YEAR, MAX(E1.SIZE_OF_COLONY) AS MAX_COLONY
FROM ECOLI_DATA E1
GROUP BY MAX_YEAR) MAX_TABLE
ON YEAR(E2.DIFFERENTIATION_DATE) = MAX_TABLE.MAX_YEAR
ORDER BY YEAR,YEAR_DEV 